### ISSUE TITLE
Can't recieve message

### ISSUE THREAD

**Issue by programmersommer** [Azure/azure-iot-connected-service#8]
I am trying your example like it's written in article [Connect your Windows app to Azure IoT Hub with Visual Studio](https://blogs.windows.com/buildingapps/2016/03/03/connect-your-windows-app-to-azure-iot-hub-with-visual-studio/) but can't read message from hub. I have tried different transport types without any result. receivedMessage inside ReceiveCloudToDeviceMessageAsync() is always null. I has event post topic on forum [Azure IoT hub reading messages issue](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/1cac75c6-bea4-468f-8961-b87001ce5350/azure-iot-hub-reading-messages-issue?forum=azureiothub)

**Comment by arturl** [comment]
Hi @programmersommer, I'm closing this as this issue is not related to the extension.
I see that your form post is not yet answered. Can you please open an issue against the Azure IoT SDK here: https://github.com/Azure/azure-iot-sdks/issues

Please include the full repro (connection string can be omitted).
